version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - copyloopvar
    - errname
    - fatcontext
    - gocritic
    - misspell
    - nilerr
    - perfsprint
    - predeclared
    - revive
    - spancheck
    - testifylint
    - unconvert
    - usestdlibvars
    - wastedassign
    - wrapcheck
    - zerologlint
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    gocritic:
      disabled-checks:
        - hugeParam
        - rangeValCopy
      enabled-tags:
        - diagnostic
        - style
        - performance
        - opinionated
    govet:
      disable:
        - fieldalignment
      enable-all: true
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: unhandled-error
          disabled: true
        - name: unused-receiver
          disabled: true
        - name: deep-exit
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: function-length
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: early-return
          disabled: true
        - name: use-any
          disabled: true
        - name: unused-parameter
          disabled: true
        - name: context-as-argument
          disabled: true
        - name: empty-block
          disabled: true
    spancheck:
      checks:
        - end
        - record-error
        - set-status
    testifylint:
      enable-all: true
      disable:
        - float-compare
        - go-require
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - errors.Join(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - gocritic
          - revive
          - wrapcheck
        path: _test\.go
      - linters:
          - gocritic
          - revive
          - wrapcheck
        path: cmd/
      - linters:
          - gocritic
          - revive
          - wrapcheck
        path: internal/testhelpers/
      - linters:
          - govet
        text: "shadow"
      - linters:
          - perfsprint
        path: "."
      - linters:
          - staticcheck
        path: "."
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
