apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingestion-gateway-staging
  namespace: argocd
spec:
  project: teampulse
  source:
    repoURL: https://github.com/kill74/TeamPulseBridge.git
    targetRevision: main
    path: deploy/k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: ingestion-gateway-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
