apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teampulse-root
  namespace: argocd
spec:
  project: teampulse
  source:
    repoURL: https://github.com/kill74/TeamPulseBridge.git
    targetRevision: main
    path: deploy/gitops/argocd/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
